from PyQt4 import QtCore, QtGui
from PyQt4.QtCore import *
from PyQt4.QtGui import *
from awsomeDialog import awsomeDialog
from awsomeDialogueButton import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class patientInfo(QtGui.QFrame):
    def __init__(self, parentForm):
        super( patientInfo, self ).__init__(parentForm)
        self.setupUi(parentForm)

    def __resizeGeometry(self,event):
        width= event.size().width()
        height= event.size().height()
        newSize = QtCore.QRect(0,0,width,height)
        self.verticalLayout_4.setGeometry(newSize)

    def setupUi(self,parent):
        self.resizeEvent = self.__resizeGeometry

        self.verticalLayout_4 = QtGui.QVBoxLayout(self)
        
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setContentsMargins(30, 0, 30, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(122, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(122, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_17 = QtGui.QLabel(self)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_7.addWidget(self.lineEdit_17, 1, 0, 1, 1)
        self.toolButton_7 = awsomeDialogButton(self)
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.gridLayout_7.addWidget(self.toolButton_7, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        spacerItem2 = QtGui.QSpacerItem(122, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_12 = QtGui.QLabel(self)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 0, 1, 1)
        self.toolButton_2 = awsomeDialogButton(self)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout_2.addWidget(self.toolButton_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem3 = QtGui.QSpacerItem(122, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_18 = QtGui.QLabel(self)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_8.addWidget(self.label_18, 0, 0, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_8.addWidget(self.lineEdit_18, 1, 0, 1, 1)
        self.toolButton_8 = awsomeDialogButton(self)
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.gridLayout_8.addWidget(self.toolButton_8, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        spacerItem4 = QtGui.QSpacerItem(122, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_19 = QtGui.QLabel(self)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_9.addWidget(self.label_19, 0, 0, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout_9.addWidget(self.lineEdit_19, 1, 0, 1, 1)
        self.toolButton_9 = awsomeDialogButton(self)
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.gridLayout_9.addWidget(self.toolButton_9, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_20 = QtGui.QLabel(self)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_10.addWidget(self.label_20, 0, 0, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout_10.addWidget(self.lineEdit_20, 1, 0, 1, 1)
        self.toolButton_10 = awsomeDialogButton(self)
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.gridLayout_10.addWidget(self.toolButton_10, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        spacerItem6 = QtGui.QSpacerItem(122, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_16 = QtGui.QLabel(self)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_6.addWidget(self.lineEdit_16, 1, 0, 1, 1)
        self.toolButton_6 = awsomeDialogButton(self)
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.gridLayout_6.addWidget(self.toolButton_6, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        spacerItem7 = QtGui.QSpacerItem(122, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_21 = QtGui.QLabel(self)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_11.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_11.addWidget(self.lineEdit_21, 1, 0, 1, 1)
        self.toolButton_11 = awsomeDialogButton(self)
        self.toolButton_11.setObjectName(_fromUtf8("toolButton_11"))
        self.gridLayout_11.addWidget(self.toolButton_11, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        spacerItem8 = QtGui.QSpacerItem(122, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem8)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_22 = QtGui.QLabel(self)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_12.addWidget(self.label_22, 0, 0, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_12.addWidget(self.lineEdit_22, 1, 0, 1, 1)
        self.toolButton_12 = awsomeDialogButton(self)
        self.toolButton_12.setObjectName(_fromUtf8("toolButton_12"))
        self.gridLayout_12.addWidget(self.toolButton_12, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_12)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem9 = QtGui.QSpacerItem(20, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.checkBox = QtGui.QCheckBox(self)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem11 = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.retranslateUi()
       

    def retranslateUi(self):
        self.label_2.setText(_translate("WizardPage", "New Patient", None))
        self.label_3.setText(_translate("WizardPage", "enter patient info", None))
        self.label_17.setText(_translate("WizardPage", "Name", None))
        self.toolButton_7.setText(_translate("WizardPage", "...", None))
        self.label_12.setText(_translate("WizardPage", "Address", None))
        self.toolButton_2.setText(_translate("WizardPage", "...", None))
        self.label_18.setText(_translate("WizardPage", "Contact Number", None))
        self.toolButton_8.setText(_translate("WizardPage", "...", None))
        self.label_19.setText(_translate("WizardPage", "CareCard", None))
        self.toolButton_9.setText(_translate("WizardPage", "...", None))
        self.label_20.setText(_translate("WizardPage", "Age", None))
        self.toolButton_10.setText(_translate("WizardPage", "...", None))
        self.label_16.setText(_translate("WizardPage", "Height", None))
        self.toolButton_6.setText(_translate("WizardPage", "...", None))
        self.label_21.setText(_translate("WizardPage", "Allergies", None))
        self.toolButton_11.setText(_translate("WizardPage", "...", None))
        self.label_22.setText(_translate("WizardPage", "Weight", None))
        self.toolButton_12.setText(_translate("WizardPage", "...", None))
        self.label.setText(_translate("WizardPage", "Sex", None))
        self.checkBox.setText(_translate("WizardPage", "Male", None))
        self.checkBox_2.setText(_translate("WizardPage", "Female", None))

       
       

 